### ISSUE TITLE
Tracking progress for Validating forks and  Rollbacks

### ISSUE THREAD

**Issue by AhmadAshraf2** [twilight-project/forkscanner#13]
This service validates folks and makes roll backs where needed.

- [ ] [find any missing blocks](https://github.com/twilight-project/forkscanner/issues/15) 
- [ ] [Chaintip Level Validation](https://github.com/twilight-project/forkscanner/issues/16)
- [ ] [Block level validation](https://github.com/twilight-project/forkscanner/issues/17)
- [ ] [make Active on mirror and roll backs](https://github.com/twilight-project/forkscanner/issues/18)
