### ISSUE TITLE
Progress Tracking Fork Scanner

### ISSUE THREAD

**Issue by AhmadAshraf2** [twilight-project/forkscanner#14]
Responsibility of this Fork Scanner will be to detect forks in BTC chain. this will provide means to check if a specific transaction is in the active chain-tip or in a valid/invalid forks. Fork Scanner will also check double spent transactions (transactions which are in more then one chain-tip) and ensure that the transaction is secure.

Purpose behind writing this is to monitor the chain and making sure that the transaction is concrete and here is no possibility of it reverting.

This is a progress tracking issue and below are the subtasks:

- [ ] [Initial startup and boot strapping.](https://github.com/twilight-project/forkscanner/issues/8)
- [ ] [Validating forks and  Rollbacks](https://github.com/twilight-project/forkscanner/issues/13).
- [ ] Detecting Double spent transactions
- [ ] [Api/RPC end point](https://github.com/twilight-project/forkscanner/issues/19)
