### ISSUE TITLE
Progress tracking API/RPC

### ISSUE THREAD

**Issue by AhmadAshraf2** [twilight-project/forkscanner#19]
We need a few API/RPC calls explained below

- [ ] An API/RPC endpoint to add or remove nodes.
- [ ] An API/RPC endpoint to retrieve latest active chaintip.
- [ ] An API/RPC endpoint to retrieve latest chaintips with each status from all connected btc nodes.
- [ ] An API/RPC endpoint to check if a transaction is in active chain.
- [ ] An API end point to get a list of blocks from DB, or get by hash or height.
