### ISSUE TITLE
Progress Tracking Initial startup and boot strapping

### ISSUE THREAD

**Issue by AhmadAshraf2** [twilight-project/forkscanner#8]
Bootstrapping is done by creating a service that will query the nodes and update the DB: 

- [x] [Setup A DB using the Schema shared in the spec sheet](https://github.com/twilight-project/forkscanner/issues/9).
- [x] [Setup some bitcoin nodes in different geographical locations](https://github.com/twilight-project/forkscanner/issues/10).
- [ ] [automate setting up of btc nodes](https://github.com/twilight-project/forkscanner/issues/11)
- [ ] setup a system so that nodes can get a list of peers from other nodes.
- [x] [Retrieve data from nodes and populate the DB.](https://github.com/twilight-project/forkscanner/issues/12)
